study_log_app/urls.py
from django.urls import path
from . import views

app_name = 'study_log_app'


urlpatterns=[
    #home
    path('',views.index,name='index'), #2nd argument to specify which function to call
                                      #3rd argument ,the name to use whenever we want to provide a link to the home page
    #topics page 
    path('topics/',views.topics,name='topics'),

    #single topic page
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    #adding topics page
    path('new_topic/',views.new_topic,name='new_topic'),

    #edit_topic
    path('edit_topic/<int:topic_id>/',views.edit_topic,name='edit_topic'),
     
    #adding new entry page
    path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),

    #edit entry
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),

]

studylog/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('study_log_app.urls')), #including all the urls in the study_log_app
    path('',include('usersapp.urls',namespace='usersapp')),#including all the urls in the usersapp
]

usersapp/urls.py
from django.urls import path, include #include imports default authentication  url patterns such login and logout
from . import views


app_name='usersapp'

urlpatterns=[
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register')

]

study_log_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    the_topic=models.CharField(max_length=200)
    input_date=models.DateTimeField(auto_now_add=True) #auto now add automatically sets the attribute 
                                                      #to the current date and time. 


    owner=models.ForeignKey(User,on_delete=models.CASCADE) #when a user is deleted all the topics associated with it are also deleted
    def __str__(self):
        return self.the_topic #displays a simple rep of the model

class Entry(models.Model):
    topic= models.ForeignKey(Topic,on_delete=models.CASCADE) #when a topic is deleted,the enteries associated with it are also deleted
    text=models.TextField()
    input_date=models.DateTimeField(auto_now_add=True) 

    class Meta: 
        verbose_name_plural='entries'     

    def __str__(self):
        return f"{self.text[:50]}..."

usersapp/models.py
from django.db import models

# Create your models here.

study_log_app/forms.py
from django import forms
from django.forms import widgets
from .models import Topic,Entry

class TopicForm(forms.ModelForm): #Allowing users to add their own  topics.
    class Meta:
        model =Topic
        fields =['the_topic']
        labels = {'the_topic':''}
class EntryForm(forms.ModelForm):
    class Meta:
        model =Entry
        fields =['text']
        labels = {'text':'Entry:'}
        widgets ={'text':forms.Textarea (attrs= {'cols':80})}

study_log_app/views.py
from django.shortcuts import render ,redirect #to redirect the user to the topics page once they have added their topic
from .models import Topic,Entry
from .forms import TopicForm,EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

def index(request):
    return render(request,'study_log_app/index.html')
    
@login_required
def topics(request):
    topics=Topic.objects.filter(owner=request.user).order_by('input_date')#tells django to retrieve info whose owner attributes matches the current user.
    context={'topics':topics}
    return render(request,'study_log_app/topics.html',context)   


@login_required
def topic(request,topic_id):
    # topic=Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    if topic.owner != request.user:
        raise Http404
    
    entries=topic.entry_set.order_by('-input_date')
    context={'topic':topic,'entries':entries}
    return render(request,'study_log_app/topic.html',context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form =TopicForm()
    else: 
        #posting the data submitted
        form =TopicForm(request.POST,request.FILES)
        if form.is_valid(): #validating that all fields are filled in correctly
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            form.save() #writes data to the database if the else condition is met
            return redirect('study_log_app:topics')
    context={'form':form}        
    return render(request,'study_log_app/new_topic.html', context)

@login_required
def edit_topic(request,topic_id):
        topic=Topic.objects.get(id=topic_id)
        if request.method!='POST':
            form =TopicForm(instance=topic)
        else:
            form =TopicForm(request.FILES,instance=topic,data=request.POST)    
            if form.is_valid():
                form.save()
                return redirect('study_log_app:topic',topic_id=topic.id)    

        context={'topic':topic, 'form':form}
        return render(request,'study_log_app/edit_topic.html',context)
                

@login_required
def new_entry(request,topic_id):
    topic=Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm() 
    else:
        form =EntryForm(request.POST,request.FILES)  
        if form.is_valid():
            new_entry =  form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('study_log_app:topic',topic_id = topic.id)
    context = {'topic':topic,'form':form}  
    return render(request,'study_log_app/new_entry.html',context) 


@login_required
def edit_entry(request,entry_id):
    entry=Entry.objects.get(id=entry_id)
    topic =entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form =EntryForm(instance=entry)
    else:
        form =EntryForm(request.FILES,instance=entry,data=request.POST)    
        if form.is_valid():
            form.save()
            return redirect('study_log_app:topic',topic_id = topic.id)    

    context={'entry':entry,'topic':topic, 'form':form}
    return render(request,'study_log_app/edit_entry.html',context)

# def delete_topic(request):

       

usersapp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login


# Create your views here.
def register(request):
    if request.method!='POST': 
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST,request.FILES)
        if form.is_valid:
            new_user=form.save()
            login(request,new_user)
            return redirect('study_log_app:index')    


    context={'form': form}
    return render(request,'registration/register.html',context)

study_log_app/templates/study_log_app/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1,
shrink-to-fit=no">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200&display=swap" rel="stylesheet">
<title>cH STUDY LOG</title>
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
 </head>
    <body style="background-color: rgb(160, 156, 156);">
         <div>
             <div>
                 
        <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border" >
         <a class="navbar-brand" href="{% url 'study_log_app:index' %}" style="font-size: 45px; color: rgb(60, 5, 61);font-family: 'Cinzel', serif;">
        cH STUDY LOG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'study_log_app:topics' %}" style="font-size: 25px;
             color: rgb(60, 5, 61);
             margin-left: 10%;font-family: 'Cinzel', serif;
             ">
            TOPICS</a></li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'usersapp:logout' %}" style="font-size: 20px; color: rgb(60, 5, 61);font-family: 'Cinzel', serif;">LOG OUT</a>
                </li>
                {% else %}
                <li class="nav-item">
                <p style=" color: rgb(60, 5, 61);font-size: 17px; margin:0 0 0 8px;font-family: 'Montserrat', sans-serif;font-weight: bold;">Don't have an account?</p><a class="nav-link" href="{% url 'usersapp:register' %}" style="font-size: 25px; color: rgb(60, 5, 61);font-family: 'Cinzel', serif;">REGISTER</a>
                </li>
                <li class="nav-item">
                {% endif %}
                </ul>
               </div>
                </div>
                </nav>
                
                <main role="main" class="container">
                    <div class="pb-2 mb-2 border-bottom">
                    {% block page_header %}{% endblock page_header %}
                    </div>
                    <div>
                    {% block content %}{% endblock content %}
                    </div>
                    </main>
                    </body>
                    </html>

study_log_app/templates/study_log_app/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <title>Document</title>
</head>
<body>
    {% extends 'study_log_app/base.html' %}
   
    
    {% block content %}
    <p id="thetopic" style="font-size: 40px;"><a href="{% url 'study_log_app:topic' topic.id %}" style="color: rgb(60, 5, 61);">{{ topic|capfirst }}</a></p>
    <p id="editentry" style="font-size:20px;color: rgb(60, 5, 61);">EDIT ENTRY:</p>
    <form action="{% url 'study_log_app:edit_entry' entry.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" style=" border-radius: 10px;
        border: solid rgb(60, 5, 61);
        padding: 10px;">SAVE CHANGES</button>
    </form>
    {% endblock content %}

   
</body>
</html>

study_log_app/templates/study_log_app/edit_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'study_log_app/base.html' %}
    {% block content %}
    <p><a href="{% url 'study_log_app:topic' topic.id %}" style="font-size: 40px;
        color: rgb(60, 5, 61);">{{ topic|capfirst }}</a></p>
    <p style="font-size: 25px;
    color: rgb(60, 5, 61);">Edit Topic:</p>
    <form action="{% url 'study_log_app:edit_topic' topic.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" style="font-size: 20px;color:  rgb(38, 3, 41);border-radius: 10px; border: solid rgb(60, 5, 61);"
        >SAVE CHANGES</button>
    </form>
    <style>
        input{
            width: 40%;
            font-size: 25px;
            border-radius: 10px;
        }
    </style>
    {% endblock content %}


</body>
</html>

study_log_app/templates/study_log_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
   
 
    <title>Document</title>
</head>
<body >
    {% extends "study_log_app/base.html" %}
    {% block content %}
    <div id="stmtbody" style="background-color: rgb(230, 225, 225);border-radius: 10px; margin-top: 3%;display: flex;margin-bottom: 5%;">
    <img src="https://i.pinimg.com/564x/7a/38/ff/7a38ff8d4c1583ec66bb89dac45c291c.jpg" height="500px" style="padding: 15px;" >
     <p style=" color: rgb(60, 5, 61); font-size: 35px;text-align: center;margin-left: 10px;margin-top: 90px;font-family: 'Montserrat', sans-serif;">
        <span class="navbar-text" style="font-size: 30px;margin-right: 10%; color: rgb(60, 5, 61);font-family: 'Cinzel', serif;">Hello, {{ user.username }}.</span>
        <br>Study log helps you Keep track of your learning experiences.
           Document your learning<br> all in one place <br>
           {% if user.is_authenticated != True %}
           <a class="nav-link" href="{% url 'usersapp:login' %}" 
           style="font-size: 25px; 
           color: rgb(60, 5, 61);
           font-family: 'Cinzel', serif;
           border: solid rgb(60, 5, 61);
           border-radius: 10px;
           width: 40%;
           margin: 10% 0 0 25%;
         
           ">LOG IN</a></li>
           {% endif %}

       
         </p>
        </div>
         
     {% endblock content %}
</body>
</html>

study_log_app/templates/study_log_app/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'study_log_app/base.html' %}
    {% block content %}
    <p><a href="{% url 'study_log_app:new_entry' topic.id %}"style="font-size: 35px;
        color: rgb(60, 5, 61);" > {{ topic|upper }}</a></p>
   <p style="font-size: 20px;
   color: rgb(60, 5, 61);">ADD ENTRY</p>
   <form action="{% url 'study_log_app:new_entry' topic.id %}" method="post" enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.as_p }}
   <button name="submit" style="font-size: 15px;
   color: rgb(60, 5, 61); border-radius: 10px;
  border: solid rgb(60, 5, 61) -1px;
  padding: 10px;">ADD ENTRY</button>

</form>



    {% endblock content %}
    
</body>
</html>

study_log_app/templates/study_log_app/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'study_log_app/base.html' %}
    {% block content %}
    <p style="font-size: 25px;color:  rgb(38, 3, 41);">ADD A TOPIC:</p>
    <form action="{% url 'study_log_app:new_topic' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}  <!-- prevent attackers from gaining aunauthorized access to the server  -->
    
     {{ form.as_p }}  <!-- creates all the fields necessary to display the form automatically,the p tells django to display theform in paragraph format  -->
     <button name="submit" style="font-size: 25px;color:  rgb(38, 3, 41);border-radius: 10px; border: solid rgb(60, 5, 61); ">ADD TOPIC</button>
    </form>
    <style>
        input{
            width: 40%;
            border-radius: 10px;
         font-size: 25px;
         
        }
    </style>
   
    {% endblock content %}
    
</body>
</html>

study_log_app/templates/study_log_app/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'study_log_app/base.html' %}
    {% block content %}
    <p style="font-size: 30px;
    color: rgb(60, 5, 61);margin-left: 4%;margin-bottom: 3%;">{{ topic|upper }}</p>

   
    <p><a href="{% url 'study_log_app:new_entry' topic.id %}" style="font-size: 15px;
        color: rgb(60, 5, 61); border-radius: 15px;
  border: solid rgb(60, 5, 61);
  padding: 10px;margin-left: 4%;">ADD ENTRY</a></p>
   <p style="font-size: 25px;
   color: rgb(60, 5, 61);margin-top: 4%;margin-left: 4%;">TOPIC ENTRIES: </p>
    <ul style="font-size: 20px;
    color: rgb(60, 5, 61);margin-top: 0;">
    {% for entry in entries %}
    <li style="background-color: rgb(230, 225, 225);height: 150px;border-radius: 10px;padding: 15px;list-style: none;">
        <p>{{ entry.input_date|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p><a href="{% url 'study_log_app:edit_entry' entry.id %}" style="font-size: 12px;
            color: rgb(60, 5, 61); border-radius: 10px;
  border: solid rgb(60, 5, 61);
  padding: 7px;">EDIT ENTRY</a></p>
    </li>
    {% empty %}
        <li>No entries have been made.</li>
    {% endfor %}
</ul>

{% endblock content %}   
</body>
</html> 

study_log_app/templates/study_log_app/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% extends 'study_log_app/base.html' %}
{% block content %}
<p style="font-size: 35px;color: rgb(60, 5, 61);">TOPICS</p>
<p style="font-size: 20px;color: rgb(60, 5, 61);font-style: italic;">Click on a topic to write what you have learnt: </p>
<ul style="margin-bottom: 4%;">
{% for topic in topics %}
<li style=" background-color: rgb(216, 210, 210);
margin-top: 10px;
height: 50px;
list-style: none;
border-radius: 10px;
padding: 17px; ">
    <a href="{% url 'study_log_app:topic' topic.id %}" style="font-size: 20px;
    color: rgb(60, 5, 61);" >{{ topic|title }}
    <a style="padding-right: 0;" href="{% url 'study_log_app:edit_topic' topic.id %}"><img style="margin-left: 40px;" src="https://bit.ly/3j5Pmq0" width="20px" height="20px"></a>
</li>
{% empty %}
<li style="font-size: 20px;margin-top: 5%;">No topics have been added yet.</li>
{% endfor %}
</ul>

<a href="{% url 'study_log_app:new_topic' %}"
 style="font-size: 20px;
 color: rgb(60, 5, 61);
  border-radius: 10px;
  border: solid rgb(60, 5, 61);
  padding: 10px;

  ">ADD TOPIC</a>


{% endblock content %}   
</body>
</html>